# Generated by Django 2.0.7 on 2018-12-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course Code', max_length=10),
        ),
    ]
