# Generated by Django 2.0.7 on 2018-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_auto_20181212_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresult',
            name='average_score',
        ),
        migrations.AddField(
            model_name='courseresult',
            name='grade',
            field=models.FloatField(blank=True, help_text='What is the grade?', null=True),
        ),
    ]
