# Generated by Django 2.0.7 on 2018-12-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_auto_20181213_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='average',
        ),
        migrations.RemoveField(
            model_name='result',
            name='remark',
        ),
        migrations.AddField(
            model_name='result',
            name='gpa',
            field=models.FloatField(help_text='What is the Grade Point Average (GPA)?', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='total_units',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Total units for the semester'),
        ),
    ]
