# Generated by Django 2.0.7 on 2018-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_auto_20181214_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='student_type',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('P', 'Part Time')], help_text='Student Type', max_length=50),
        ),
    ]
