# Generated by Django 2.0.7 on 2019-01-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0006_programme_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Your Department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='cbt.Department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='entry_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Admission year. (e.g. 2018)'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='graduation_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Graduation year. (e.g. 2022)'),
        ),
    ]
