# Generated by Django 2.0.7 on 2019-01-08 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt', '0007_auto_20190108_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Access Token', max_length=250)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2)),
                ('course', models.ForeignKey(help_text='Generate token for what course?', on_delete=django.db.models.deletion.CASCADE, related_name='token_course', to='cbt.Course')),
                ('user', models.OneToOneField(help_text='Generate Token for User.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
