# Generated by Django 2.0.7 on 2019-01-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt', '0008_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text="Student's level", max_length=3)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text="Student's semester", max_length=2)),
                ('course', models.ForeignKey(help_text='What course are you registering?', on_delete=django.db.models.deletion.CASCADE, related_name='registered_course', to='cbt.Course')),
                ('user', models.OneToOneField(help_text='Student registering course', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'permissions': (('create_token', 'Can create token for users'), ('flush_token', 'Can flush/delete tokens'))},
        ),
    ]
