# Generated by Django 2.0.7 on 2019-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_auto_20190108_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2),
        ),
    ]
