# Generated by Django 2.0.7 on 2019-01-09 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0010_auto_20190108_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(help_text='Student registering course', on_delete=django.db.models.deletion.CASCADE, related_name='register_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
