# Generated by Django 2.0.7 on 2019-01-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0011_auto_20190109_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(help_text='Generate Token for User.', on_delete=django.db.models.deletion.CASCADE, to='cbt.UserDetail'),
        ),
    ]
