# Generated by Django 2.0.7 on 2019-01-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0012_auto_20190111_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='user',
            field=models.ForeignKey(help_text='Student Username', on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to='cbt.UserDetail'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(help_text='Student Username', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cbt.UserDetail'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(help_text='Student registering course', on_delete=django.db.models.deletion.CASCADE, related_name='register_course', to='cbt.UserDetail'),
        ),
    ]
