# Generated by Django 2.0.7 on 2019-01-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0013_auto_20190111_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(help_text='Student Username', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='cbt.UserDetail'),
        ),
    ]
