# Generated by Django 3.1.1 on 2020-09-28 11:40

import cbt.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0016_auto_20200927_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(help_text='Student username', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='cbt.userdetail'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is the answer meant for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='answer',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is the answer meant for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Choose your answer', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(help_text='Name of country', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course code', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Select department', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='cbt.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Course title', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.SmallIntegerField(verbose_name='Course credit unit'),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is this course for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='score',
            field=models.SmallIntegerField(help_text='What is the score?'),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is this course for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='user',
            field=models.ForeignKey(help_text='Student username', on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to='cbt.userdetail'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(help_text='Name of department', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(help_text='Name of faculty', max_length=200),
        ),
        migrations.AlterField(
            model_name='kin',
            name='phone',
            field=models.IntegerField(blank=True, help_text="Next of Kin's mobile No.", null=True),
        ),
        migrations.AlterField(
            model_name='kin',
            name='relationship',
            field=models.CharField(blank=True, choices=[('', None), ('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('U', 'Uncle'), ('O', 'Others')], help_text='How are you related?', max_length=2),
        ),
        migrations.AlterField(
            model_name='lga',
            name='title',
            field=models.CharField(help_text='Name of LGA', max_length=200),
        ),
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Your department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='cbt.department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='entry_mode',
            field=models.CharField(blank=True, choices=[('U', 'UTME'), ('D', 'Direct Entry'), ('T', 'Transfer'), ('I', 'IJAMB')], help_text="Student's mode of entry.", max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='entry_year',
            field=models.SmallIntegerField(blank=True, help_text='Admission year. (e.g. 2020)', null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='graduation_year',
            field=models.SmallIntegerField(blank=True, help_text='Graduation year. (e.g. 2024)', null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='jamb_no',
            field=models.CharField(blank=True, help_text='Enter your JAMB registration number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Please select your current level.', max_length=3),
        ),
        migrations.AlterField(
            model_name='programme',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Enter your registration number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='programme',
            name='student_mode',
            field=models.CharField(blank=True, choices=[('N', 'New Student'), ('C', 'Returning Student'), ('P', 'Probation'), ('W', 'Withrawal')], help_text="Student's mode", max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='student_type',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('P', 'Part Time')], help_text='Student type', max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('F', 'Full Time'), ('P', 'Part Time')], help_text="Student's mode of study.", max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.PositiveSmallIntegerField(help_text="Input the option that is the correct answer. eg: '1' for\n        option1 or '2' for option2"),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is the question meant for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(help_text='Add option 1', max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(help_text='Add option 2', max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, help_text='Add option 3', max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, help_text='Add option 4', max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.CharField(blank=True, help_text='Add option 5', max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='What is the score of this question?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is the question meant for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What is your level.', max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester has this result?', max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_courses',
            field=models.PositiveSmallIntegerField(help_text='How many courses were offered in total?'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_score',
            field=models.SmallIntegerField(blank=True, help_text='Total score for the semester', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_units',
            field=models.SmallIntegerField(blank=True, help_text='Total units for the semester', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(help_text='Student username', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cbt.userdetail'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='address',
            field=models.CharField(blank=True, help_text="Sponsor's address", max_length=250),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.IntegerField(blank=True, help_text="Sponsor's mobile No.", null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='relationship',
            field=models.CharField(blank=True, choices=[('', None), ('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('U', 'Uncle'), ('O', 'Others')], help_text='How are you related?', max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Name of country', on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='cbt.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(help_text='Name of state', max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3),
        ),
        migrations.AlterField(
            model_name='token',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(help_text='Access token', max_length=250),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(help_text='Generate Token for user', on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='cbt.userdetail'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='level',
            field=models.CharField(choices=[('', None), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text="Student's level", max_length=3),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='semester',
            field=models.CharField(choices=[('', None), ('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text="Student's semester", max_length=2),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birth_date',
            field=models.DateTimeField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Contact address', max_length=300),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='home_town',
            field=models.CharField(blank=True, help_text='Home town', max_length=250),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last modified date'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lga',
            field=models.ForeignKey(blank=True, help_text='Local Government Area of origin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lga', to='cbt.lga'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='middle_name',
            field=models.CharField(blank=True, help_text='middle name', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='perm_address',
            field=models.CharField(blank=True, help_text='Permanent address', max_length=300),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Your mobile phone number', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pictures',
            field=models.ImageField(blank=True, help_text='Select profile picture.', upload_to=cbt.utils.u_p_path),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='religion',
            field=models.CharField(blank=True, choices=[('C', 'Christianity'), ('I', 'Islam'), ('T', 'Traditional'), ('H', 'Hinduism'), ('O', 'Others')], help_text='Please select your religion', max_length=2),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='signature',
            field=models.ImageField(blank=True, help_text='Add your signature.', upload_to=cbt.utils.u_s_path),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('E', 'Engaged'), ('D', 'Divorced'), ('S', 'Single'), ('C', 'Complicated'), ('O', 'Others')], help_text='Please select your relationship status', max_length=2),
        ),
    ]
