# Generated by Django 3.1.1 on 2020-09-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0017_auto_20200928_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of institution', max_length=200)),
                ('detail', models.TextField(help_text='Details of the institution')),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Choose the institution', on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='cbt.institution'),
            preserve_default=False,
        ),
    ]
