# Generated by Django 3.1.1 on 2020-10-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0018_auto_20200928_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['title'], 'verbose_name_plural': 'countries'},
        ),
    ]
