# Generated by Django 3.1.1 on 2020-10-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0019_auto_20201010_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is the answer meant for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='answer',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is the answer meant for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is this course for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is this course for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='kin',
            name='relationship',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('U', 'Uncle'), ('O', 'Others')], help_text='How are you related?', max_length=2),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Please select your current level.', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What level is the question meant for?', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester is the question meant for?', max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='What is your level.', max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='What semester has this result?', max_length=2),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='relationship',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('B', 'Brother'), ('S', 'Sister'), ('U', 'Uncle'), ('O', 'Others')], help_text='How are you related?', max_length=2),
        ),
        migrations.AlterField(
            model_name='token',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text='Generate token for what level?', max_length=3),
        ),
        migrations.AlterField(
            model_name='token',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text='Generate token for what semester?', max_length=2),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], default=100, help_text="Student's level", max_length=3),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default=1, help_text="Student's semester", max_length=2),
        ),
    ]
