# Generated by Django 3.1.1 on 2020-10-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account_mode',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('L', 'Lecturer'), ('D', 'Dean')], help_text='User account mode', max_length=2),
        ),
    ]
